### ISSUE TITLE
Unable to Build on Ub 16.04

### ISSUE THREAD

**Issue by vr4dude316** [bitcoin-atom/bitcoin-atom#4]
Build fails on Make Install.  All depends installed

**Comment by vr4dude316** [comment]
CXX      test/test_test_bitcoin-policyestimator_tests.o
  CXX      test/test_test_bitcoin-pow_tests.o
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work::test_meth                                                                                                             od()’:
test/pow_tests.cpp:25:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uin                                                                                                             t64_t {aka long unsigned int}’ [-fpermissive]
 Required(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00d8
                                                                     ^
In file included from ./chain.h:9:0,
                 from test/pow_tests.cpp:5:
./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arit                                                                                                             h_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}
     ^
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp:25:108: error: cannot convert ‘const Consensus::Params’ to ‘i                                                                                                             nt64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(a                                                                                                             rith_uint256, int64_t, int64_t, const Consensus::Params&)’
 Required(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00d8
                                                                     ^
test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work_pow_limit:                                                                                                             :test_method()’:
test/pow_tests.cpp:37:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uin                                                                                                             t64_t {aka long unsigned int}’ [-fpermissive]
 Required(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00ff
                                                                     ^
In file included from ./chain.h:9:0,
                 from test/pow_tests.cpp:5:
./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arit                                                                                                             h_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}
     ^
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp:37:108: error: cannot convert ‘const Consensus::Params’ to ‘i                                                                                                             nt64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(a                                                                                                             rith_uint256, int64_t, int64_t, const Consensus::Params&)’
 Required(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00ff
                                                                     ^
test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work_lower_limi                                                                                                             t_actual::test_method()’:
test/pow_tests.cpp:49:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uin                                                                                                             t64_t {aka long unsigned int}’ [-fpermissive]
 Required(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1c0168
                                                                     ^
In file included from ./chain.h:9:0,
                 from test/pow_tests.cpp:5:
./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arit                                                                                                             h_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}
     ^
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp:49:108: error: cannot convert ‘const Consensus::Params’ to ‘i                                                                                                             nt64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(a                                                                                                             rith_uint256, int64_t, int64_t, const Consensus::Params&)’
 Required(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1c0168
                                                                     ^
test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work_upper_limi                                                                                                             t_actual::test_method()’:
test/pow_tests.cpp:61:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uin                                                                                                             t64_t {aka long unsigned int}’ [-fpermissive]
 Required(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00e1
                                                                     ^
In file included from ./chain.h:9:0,
                 from test/pow_tests.cpp:5:
./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arit                                                                                                             h_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}
     ^
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp:61:108: error: cannot convert ‘const Consensus::Params’ to ‘i                                                                                                             nt64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(a                                                                                                             rith_uint256, int64_t, int64_t, const Consensus::Params&)’
 Required(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00e1
                                                                     ^
Makefile:9365: recipe for target 'test/test_test_bitcoin-pow_tests.o' failed
make[2]: *** [test/test_test_bitcoin-pow_tests.o] Error 1
make[2]: Leaving directory '/home/unomp/bitcoin-atom/src'
Makefile:9945: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/unomp/bitcoin-atom/src'
Makefile:747: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
unomp@ubuntu:~/bitcoin-atom$ Makefile:9365: recipe for target 'test/test_test_bi                                                                                                             tcoin-pow_tests.o' failed

**Comment by vr4dude316** [comment]
So sorry.  Just read the closed resolution.  Works out well
