### ISSUE TITLE
Unable to compile on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by gonzzza007** [bitcoin-atom/bitcoin-atom#3]
Git last commit: 764953a
autogen.sh - ok
configure - ok
make:

test/pow_tests.cpp:25:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]
     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00d86a);
                                                                                                            ^
In file included from ./chain.h:9:0,
                 from test/pow_tests.cpp:5:
./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arith_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}
     ^
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp:25:108: error: cannot convert ‘const Consensus::Params’ to ‘int64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(arith_uint256, int64_t, int64_t, const Consensus::Params&)’
     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00d86a);
                                                                                                            ^
test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work_pow_limit::test_method()’:
test/pow_tests.cpp:37:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]
     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00ffff);
                                                                                                            ^
In file included from ./chain.h:9:0,
                 from test/pow_tests.cpp:5:
./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arith_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}
     ^
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp:37:108: error: cannot convert ‘const Consensus::Params’ to ‘int64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(arith_uint256, int64_t, int64_t, const Consensus::Params&)’
     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00ffff);
                                                                                                            ^
test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work_lower_limit_actual::test_method()’:
test/pow_tests.cpp:49:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]
     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1c0168fd);
                                                                                                            ^
In file included from ./chain.h:9:0,
                 from test/pow_tests.cpp:5:
./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arith_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}
     ^
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp:49:108: error: cannot convert ‘const Consensus::Params’ to ‘int64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(arith_uint256, int64_t, int64_t, const Consensus::Params&)’
     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1c0168fd);
                                                                                                            ^
test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work_upper_limit_actual::test_method()’:
test/pow_tests.cpp:61:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]
     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00e1fd);
                                                                                                            ^
In file included from ./chain.h:9:0,
                 from test/pow_tests.cpp:5:
./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arith_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}
     ^
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from test/pow_tests.cpp:12:
test/pow_tests.cpp:61:108: error: cannot convert ‘const Consensus::Params’ to ‘int64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(arith_uint256, int64_t, int64_t, const Consensus::Params&)’
     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00e1fd);

**Comment by daygle** [comment]
I'm receiving the same with Debian

**Comment by pav-hash** [comment]
As I posted in another issue..
./configure --enable-tests=no

**Comment by gonzzza007** [comment]
Yes, disabling tests works! Thanks a lot.
